# -*- coding: utf-8 -*-
"""inspect_image.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WwpDllRAI_NEhi_gghjSF1EMfGQu8fCN

# Import PIL and NumPy
"""

from PIL import Image
import numpy as np

"""# Open the image file"""

img = Image.open("/content/download.jpg")

"""# Convert image to NumPy array"""

array = np.array(img)

print(array.shape)
print(array.dtype)
print(array.min())
print(array.max())

"""# Extract and print EXIF data"""

exif_data = img.getexif()
for tag_id, value in exif_data.items():
    print(tag_id, value)